workspace:
  base: /go
  path: src/github.com/chneau/chneau

pipeline:
  build:
    image: golang
    commands:
      - go get
      - go build
    when:
      branch:
        - master
        - develop
      event:
        - push
        - pull_request


  publish:
    image: plugins/docker
    username: ${docker_username}
    password: ${docker_password}
    repo: chneau/chneau
    tag:
      - latest
    file: Dockerfile
    secrets: [docker_username, docker_password]
    when:
      branch:
        - master
      event:
        - push